name: CI

on:
  push:
  pull_request:
    branches: [ main ]
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - preset: linux-amd64-release
            artifact: linux-amd64
          - preset: linux-arm64-release
            artifact: linux-arm64
            emulator: qemu-aarch64-static
          - preset: clang-tidy
          - preset: linux-sanitizer

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build cmake

      - name: CMake and Ninja
        run: |
          mkdir build
          cmake -G Ninja -S . -B build
          cd build
          ninja

      - name: Upload Distribution
        if: ${{ matrix.config.artifact != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: tup-${{ matrix.config.artifact }}
          path: build/tup

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install CMake and Ninja
        uses: seanmiddleditch/gha-setup-ninja@v5

      - name: CMake and Ninja
        run: |
          mkdir build
          cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release
          ninja

      - name: Upload Windows Distribution
        uses: actions/upload-artifact@v4
        with:
          name: tup-windows
          path: build/tup.exe
