name: CI

on:
  push:
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - preset: linux-amd64
            artifact: linux-amd64

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build cmake protobuf-compiler libtbb-dev

      - name: CMake and Ninja
        run: |
          mkdir build
          cmake -G Ninja -S . -B build
          cd build
          ninja

      - name: Upload Distribution
        uses: actions/upload-artifact@v4
        with:
          name: tup-${{ matrix.config.artifact }}
          path: build/tup-backend
